// Mocks generated by Mockito 5.4.6 from annotations
// in layers/test/project_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i6;
import 'dart:typed_data' as _i9;

import 'package:layers/core/result.dart' as _i4;
import 'package:layers/models/layer.dart' as _i8;
import 'package:layers/models/project.dart' as _i5;
import 'package:layers/services/supabase_project_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SupabaseProjectService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseProjectService extends _i1.Mock
    implements _i2.SupabaseProjectService {
  MockSupabaseProjectService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.Project>> createProject({
    required _i6.File? imageFile,
    Map<String, dynamic>? params = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createProject, [], {
              #imageFile: imageFile,
              #params: params,
            }),
            returnValue: _i3.Future<_i4.Result<_i5.Project>>.value(
              _i7.dummyValue<_i4.Result<_i5.Project>>(
                this,
                Invocation.method(#createProject, [], {
                  #imageFile: imageFile,
                  #params: params,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Project>>);

  @override
  _i3.Future<_i4.Result<_i5.Project>> getProject(String? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#getProject, [projectId]),
            returnValue: _i3.Future<_i4.Result<_i5.Project>>.value(
              _i7.dummyValue<_i4.Result<_i5.Project>>(
                this,
                Invocation.method(#getProject, [projectId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Project>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Project>>> listProjects() =>
      (super.noSuchMethod(
            Invocation.method(#listProjects, []),
            returnValue: _i3.Future<_i4.Result<List<_i5.Project>>>.value(
              _i7.dummyValue<_i4.Result<List<_i5.Project>>>(
                this,
                Invocation.method(#listProjects, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Project>>>);

  @override
  _i3.Future<_i4.Result<List<_i8.Layer>>> getProjectLayers(String? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#getProjectLayers, [projectId]),
            returnValue: _i3.Future<_i4.Result<List<_i8.Layer>>>.value(
              _i7.dummyValue<_i4.Result<List<_i8.Layer>>>(
                this,
                Invocation.method(#getProjectLayers, [projectId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i8.Layer>>>);

  @override
  _i3.Future<_i4.Result<void>> updateLayerTransform(
    String? layerId, {
    double? x,
    double? y,
    double? scale,
    double? rotation,
    double? opacity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateLayerTransform,
              [layerId],
              {
                #x: x,
                #y: y,
                #scale: scale,
                #rotation: rotation,
                #opacity: opacity,
              },
            ),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i7.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(
                  #updateLayerTransform,
                  [layerId],
                  {
                    #x: x,
                    #y: y,
                    #scale: scale,
                    #rotation: rotation,
                    #opacity: opacity,
                  },
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> updateLayerVisibility(
    String? layerId,
    bool? visible,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLayerVisibility, [layerId, visible]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i7.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#updateLayerVisibility, [layerId, visible]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> updateLayerOrder(String? layerId, int? zIndex) =>
      (super.noSuchMethod(
            Invocation.method(#updateLayerOrder, [layerId, zIndex]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i7.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#updateLayerOrder, [layerId, zIndex]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteProject(String? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProject, [projectId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i7.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteProject, [projectId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Stream<_i5.Project> subscribeToProject(String? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToProject, [projectId]),
            returnValue: _i3.Stream<_i5.Project>.empty(),
          )
          as _i3.Stream<_i5.Project>);

  @override
  _i3.Future<String> getSignedUrl(String? bucket, String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getSignedUrl, [bucket, path]),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getSignedUrl, [bucket, path]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<_i9.Uint8List> downloadFile(String? bucket, String? path) =>
      (super.noSuchMethod(
            Invocation.method(#downloadFile, [bucket, path]),
            returnValue: _i3.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
          )
          as _i3.Future<_i9.Uint8List>);
}
